codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "10...100"
  status:
    project:
      default:
        # basic
        target: 85%
        threshold: 1%
        base: auto 
    patch:
      default:
        # basic
        target: 0%
        threshold: 1%
        base: auto 