codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        base: auto 
    patch:
      default:
        # basic
        target: 50%
        threshold: 1%
        base: auto 